############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1


[[main]]
name = "About Us"
pageRef = "/about/"
weight = 2

[[main]]
name = "Contact Us"
pageRef = "/contact/"
weight = 3

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 4


# footer menu
[[footer]]
name = "Home"
pageRef = "/"
weight = 1

[[footer]]
name = "About Us"
pageRef = "/about/"
weight = 2

[[footer]]
name = "Contact Us"
pageRef = "/contact/"
weight = 3

[[footer]]
name = "Blog"
pageRef ="/blog/
weight = 4
