############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Services"
pageRef = "/services/"
weight = 2

[[main]]
name = "About Us"
pageRef = "/about/"
weight = 3


[[main]]
name = "Contact Us"
pageRef = "/contact/"
weight = 4

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 5


# footer menu
[[footer]]
name = "Home"
pageRef = "/"
weight = 1

[[footer]]
name = "About Us"
pageRef = "/about/"
weight = 2

[[footer]]
name = "Contact Us"
pageRef = "/contact/"
weight = 3

[[footer]]
name = "Blog"
pageRef ="/blog/"
weight = 4
